"""
PVG 2023
Project: Binary Strike (Platformer)

Author: Alejandro Mujica
alejandro.j.mujic4@gmail.com

Author: Kevin Márquez
marquezberriosk@gmail.com

Author: Lewis Ochoa
lewis8a@gmail.com

This file contains the definition for tiles.
"""
from typing import Dict, Any

TILES_1: Dict[int, Dict[str, Any]] = {
    #Ground Level 1
    0: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    1: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    2: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    3: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    4: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    5: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    6: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    7: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    80: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    81: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    82: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    83: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    216: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    217: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    218: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    219: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    220: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    221: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    222: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    223: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    288: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    289: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    290: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    291: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    292: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    293: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    366: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    367: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    368: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    369: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    508: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    509: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    510: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    511: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    516: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    517: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    518: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    519: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    580: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    581: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    588: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    589: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    652: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    653: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    660: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    661: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
}

TILES_2: Dict[int, Dict[str, Any]] = {
    # Ground Level 2
    6: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    7: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    8: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    9: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    10: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    11: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    16: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    17: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    34: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    35: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    48: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    49: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    52: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    53: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    60: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    61: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    62: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    63: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    64: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    65: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    70: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    71: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    102: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    103: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    108: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    109: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    110: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    111: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    112: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    113: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    114: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    115: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    116: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    117: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    118: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    119: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    120: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    121: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    122: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    123: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    124: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    125: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    126: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    127: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    128: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    129: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    130: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    131: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    132: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    133: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    134: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    135: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    136: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    137: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    138: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    139: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    140: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    141: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    142: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    143: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    144: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    145: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    146: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    147: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    148: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    149: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    150: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    151: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    152: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    153: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    154: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    155: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    156: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    157: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    158: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    159: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    160: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    168: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    169: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    170: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    171: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    172: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    173: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    178: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    179: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    204: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    205: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    206: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    207: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    208: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    209: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    210: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    211: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    222: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    223: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    224: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    225: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    226: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    227: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    228: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    229: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    230: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    231: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    232: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    233: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    258: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    259: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    260: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    261: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    262: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    263: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    264: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    265: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    270: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    271: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    272: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    273: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    274: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    275: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    276: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    277: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    278: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    279: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    280: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    281: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    282: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    283: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    284: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    285: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    286: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    287: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    288: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    289: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    290: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    291: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    291: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    292: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    293: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    294: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    295: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    296: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    297: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    298: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    299: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    300: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    301: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    302: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    303: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    306: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    307: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
}

TILES_3: Dict[int, Dict[str, Any]] = {
    # Ground Level 3
    0: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    1: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    2: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    39: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    51: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    52: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    53: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    143: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    144: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    145: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    149: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    150: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    193: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    194: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    195: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    196: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    211: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
    212: {"solidness": dict(top=True, right=False, bottom=False, left=False)},
}